// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvzymjNHR9rtYDAKx2vjQ--W21JcWK0I',
    appId: '1:829183789979:web:00f10d97597a4260f42f3e',
    messagingSenderId: '829183789979',
    projectId: 'android-app-a68f0',
    authDomain: 'android-app-a68f0.firebaseapp.com',
    storageBucket: 'android-app-a68f0.firebasestorage.app',
    measurementId: 'G-STBFFHYRKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXrpCeRYSSdxreOvy_EKiv_U39jC3Vw0',
    appId: '1:829183789979:android:5e728e764215b344f42f3e',
    messagingSenderId: '829183789979',
    projectId: 'android-app-a68f0',
    storageBucket: 'android-app-a68f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACugl3ft3TaX-1CaoM2lkwPjessFIY-Gk',
    appId: '1:829183789979:ios:bd11ee42450b0370f42f3e',
    messagingSenderId: '829183789979',
    projectId: 'android-app-a68f0',
    storageBucket: 'android-app-a68f0.firebasestorage.app',
    iosBundleId: 'com.example.ict602Carrymark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACugl3ft3TaX-1CaoM2lkwPjessFIY-Gk',
    appId: '1:829183789979:ios:bd11ee42450b0370f42f3e',
    messagingSenderId: '829183789979',
    projectId: 'android-app-a68f0',
    storageBucket: 'android-app-a68f0.firebasestorage.app',
    iosBundleId: 'com.example.ict602Carrymark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjvzymjNHR9rtYDAKx2vjQ--W21JcWK0I',
    appId: '1:829183789979:web:00f10d97597a4260f42f3e',
    messagingSenderId: '829183789979',
    projectId: 'android-app-a68f0',
    authDomain: 'android-app-a68f0.firebaseapp.com',
    storageBucket: 'android-app-a68f0.firebasestorage.app',
    measurementId: 'G-STBFFHYRKL',
  );
}
